set $focus #ff0000
set $nofocus #00ff00
set $titletxt #000000

client.focused          $focus   $focus   $titletxt $focus    $focus
client.focused_inactive $nofocus $nofocus $titletxt $nofocus  $nofocus
client.unfocused        $nofocus $nofocus $titletxt $nofocus  $nofocus
client.urgent           $nofocus $nofocus $titletxt $nofocus  $nofocus

