output HDMI-A-1 {
    mode 1920x1080@75Hz
    transform 180
    subpixel none
    background #fefefe solid_color
    allow_tearing no
    max_render_time off
    adaptive_sync off
}

output eDP-1 disable
# output eDP-1 {
#     disable
    # mode 1366x768@60Hz
# }

# output * {
#     subpixel none
#     background #f8f8f8 solid_color
#     allow_tearing no
#     max_render_time off
#     adaptive_sync off
# }
#
