local ops = {
    fo = 'jql',
    cuc = true,
    cul = true,
    ea = false,
    ar = true,
    aw = false,
    et = true,
    hid = true,
    fen = false,
    smd = false,
    swf = false,
    timeout = false,
    ttimeoutlen = 1000,
    ws = false,
    nu = true,
    rnu = true,
    sc = true,
    udf = true,
    wfh = true,
    wfw = true,
    cc = '+1',
    cole = 3,
    fcs = 'eob: ',
    fdc = '0',
    fdm = 'expr',
    ls = 3,
    mopt = 'hit-enter,history:10000',
    mouse = '',
    nuw = 3,
    report = 999999,
    cpoptions = 'aAceFs_',
    scbk = 100000,
    scl = 'number',
    shm = 'aotTOsWAIcCFq',
    sloc = 'statusline',
    so = 5,
    stc = '%s%C%l',
    sts = -1,
    sw = 4,
    ts = 4,
    tw = 80,
    ul = 999999,
    ur = 999999,
    completeopt = { 'menuone', 'popup', 'noinsert', 'noselect' },
    sessionoptions = {
        'buffers', 'curdir', 'folds', 'help', 'resize', 'tabpages', 'terminal',
        'winpos', 'winsize',
    },
}

for o, v in pairs(ops) do pcall(function() vim.opt[o] = v end) end

