vim.keymap.set(
    { 'n' }, '<Esc>', function()
        vim.cmd 'nohlsearch'
        return '<Esc>'
    end, { remap = true })
vim.keymap.set({ 'v' }, '<', '<gv')
vim.keymap.set({ 'v' }, '>', '>gv')
vim.keymap.set({ 'n' }, 'n', 'nzz')
vim.keymap.set({ 'n' }, 'N', 'Nzz')
vim.keymap.set({ 'n' }, 'L', '<cmd>bn<cr>', { desc = 'Next Buffer' })
vim.keymap.set({ 'n' }, 'H', '<cmd>bp<cr>', { desc = 'Prev Buffer' })
vim.keymap.set({ 'n' }, '<', '<<')
vim.keymap.set({ 'n' }, '>', '>>')
vim.keymap.set({ 'n', 't' }, '<A-j>', '<C-w>j')
vim.keymap.set({ 'n', 't' }, '<A-k>', '<C-w>k')
vim.keymap.set({ 'n', 't' }, '<A-l>', '<C-w>l')
vim.keymap.set({ 'n', 't' }, '<A-h>', '<C-w>h')
vim.keymap.set({ 'n', 't' }, '<A-d>', '<cmd>Bwipeout<cr>')
vim.keymap.set({ 'n' }, '<A-L>', '<C-w>L')
vim.keymap.set({ 'n' }, '<A-H>', '<C-w>H')
vim.keymap.set({ 'n' }, '<A-o>', '<C-w>o')
vim.keymap.set({ 'n', 't' }, '<A-c>', '<C-w>c')
vim.keymap.set({ 'n' }, '<A-s>', '<C-w>s')
vim.keymap.set({ 'n' }, '<A-v>', '<C-w>v')
vim.keymap.set({ 'n' }, '<A-t>', '<C-w>T')
vim.keymap.set({ 'n' }, '<A-,>', '<C-w><')
vim.keymap.set({ 'n' }, '<A-.>', '<C-w>>')
vim.keymap.set({ 'n' }, '<A-->', '<C-w>-')
vim.keymap.set({ 'n' }, '<A-=>', '<C-w>+')
vim.keymap.set({ 'n' }, '<A-;>', '<C-w>=')
vim.keymap.set({ 'n', 'v' }, 'gy', '"+y')
vim.keymap.set({ 'n' }, 'gp', '"+p')
vim.keymap.set({ 'n', 'v' }, 'gY', '"+Y')
vim.keymap.set({ 'n' }, 'gP', '"+P')
vim.keymap.set({ 'i' }, '<C-j>', '<Esc>o')
vim.keymap.set({ 'i' }, '<A-h>', '<C-o>h')
vim.keymap.set({ 'i' }, '<A-j>', '<C-o>j')
vim.keymap.set({ 'i' }, '<A-k>', '<C-o>k')
vim.keymap.set({ 'i' }, '<A-l>', '<C-o>l')
vim.keymap.set({ 'i' }, '<A-b>', '<C-o>b')
vim.keymap.set({ 'i' }, '<A-w>', '<C-o>w')
vim.keymap.set({ 'i' }, '<A-e>', '<C-o>e')
vim.keymap.set({ 'i' }, '<A-,>', '<Esc>I')
vim.keymap.set({ 'i' }, '<A-.>', '<Esc>A')
vim.keymap.set({ 'c' }, '<A-h>', '<Left>')
vim.keymap.set({ 'c' }, '<A-j>', '<Down>')
vim.keymap.set({ 'c' }, '<A-k>', '<Up>')
vim.keymap.set({ 'c' }, '<A-l>', '<Right>')
vim.keymap.set({ 'c' }, '<A-,>', '<Home>')
vim.keymap.set({ 'c' }, '<A-.>', '<End>')
vim.keymap.set({ 't' }, '<Esc><Esc>', '<C-\\><C-n>')
vim.keymap.set({ 'n' }, 'çtw', '<Cmd>term<CR>')
vim.keymap.set({ 'n' }, 'çtv', '<Cmd>vertical term<CR>')
vim.keymap.set({ 'n' }, 'çts', '<Cmd>horizontal term<CR>')
