return {
    { 'loganswartz/polychrome.nvim', event = 'VeryLazy' },
    { 'rktjmp/lush.nvim', event = 'VeryLazy' },
    -- '0xstepit/flow.nvim',
    { '2nthony/vitesse.nvim', event = 'VeryLazy' },
    { 'Abstract-IDE/Abstract-cs', event = 'VeryLazy' },
    { 'AlessandroYorba/Alduin', event = 'VeryLazy' },
    { 'AlexvZyl/nordic.nvim', event = 'VeryLazy' },
    { 'ChristianChiarulli/nvcode-color-schemes.vim', event = 'VeryLazy' },
    { 'DilanGMB/nightbuddy', event = 'VeryLazy' },
    { 'EdenEast/nightfox.nvim', event = 'VeryLazy' },
    { 'Everblush/nvim', event = 'VeryLazy' },
    { 'FrenzyExists/aquarium-vim', event = 'VeryLazy' },
    -- 'HoNamDuong/hybrid.nvim',
    { 'Iron-E/nvim-highlite', event = 'VeryLazy' },
    { 'Matsuuu/pinkmare', event = 'VeryLazy' },
    { 'Mofiqul/adwaita.nvim', event = 'VeryLazy' },
    { 'Mofiqul/dracula.nvim', event = 'VeryLazy' },
    { 'Mofiqul/vscode.nvim', event = 'VeryLazy' },
    { 'MordechaiHadad/nvim-papadark', event = 'VeryLazy' },
    { 'NTBBloodbath/doom-one.nvim', event = 'VeryLazy' },
    -- 'PHSix/nvim-hybrid',
    { 'PyGamer0/darc.nvim', event = 'VeryLazy' },
    { 'RRethy/base16-nvim', event = 'VeryLazy' },
    -- 'RRethy/nvim-base16',
    { 'RishabhRD/gruvy', event = 'VeryLazy' },
    -- 'Shatur/neovim-ayu',
    -- 'Th3Whit3Wolf/one-nvim',
    -- 'Th3Whit3Wolf/onebuddy',
    -- 'Th3Whit3Wolf/space-nvim',
    { 'Tsuzat/NeoSolarized.nvim', event = 'VeryLazy' },
    { 'Verf/deepwhite.nvim', event = 'VeryLazy' },
    { 'Yagua/nebulous.nvim', event = 'VeryLazy' },
    { 'Yazeed1s/minimal.nvim', event = 'VeryLazy' },
    { 'Yazeed1s/oh-lucy.nvim', event = 'VeryLazy' },
    { 'adigitoleo/vim-mellow', event = 'VeryLazy' },
    { 'adisen99/apprentice.nvim', event = 'VeryLazy' },
    { 'adisen99/codeschool.nvim', event = 'VeryLazy' },
    { 'alexmozaidze/palenight.nvim', event = 'VeryLazy' },
    { 'andersevenrud/nordic.nvim', event = 'VeryLazy' },
    { 'askfiy/visual_studio_code', event = 'VeryLazy' },
    { 'bakageddy/alduin.nvim', event = 'VeryLazy' },
    -- 'bkegley/gloombuddy',
    { 'bluz71/vim-moonfly-colors', event = 'VeryLazy' },
    { 'bluz71/vim-nightfly-colors', event = 'VeryLazy' },
    { 'bluz71/vim-nightfly-guicolors', event = 'VeryLazy' },
    { 'briones-gabriel/darcula-solid.nvim', event = 'VeryLazy' },
    { 'calind/selenized.nvim', event = 'VeryLazy' },
    { 'catppuccin/nvim', event = 'VeryLazy' },
    { 'chrsm/paramount-ng.nvim', event = 'VeryLazy' },
    { 'comfysage/evergarden', event = 'VeryLazy' },
    { 'cpea2506/one_monokai.nvim', event = 'VeryLazy' },
    { 'cryptomilk/nightcity.nvim', event = 'VeryLazy' },
    { 'dasupradyumna/midnight.nvim', event = 'VeryLazy' },
    { 'datsfilipe/min-theme.nvim', event = 'VeryLazy' },
    { 'datsfilipe/vesper.nvim', event = 'VeryLazy' },
    { 'diegoulloao/neofusion.nvim', event = 'VeryLazy' },
    { 'dracula/vim', event = 'VeryLazy' },
    { 'echasnovski/mini.nvim', event = 'VeryLazy' },
    { 'elianiva/gruvy.nvim', event = 'VeryLazy' },
    { 'elianiva/icy.nvim', event = 'VeryLazy' },
    { 'ellisonleao/gruvbox.nvim', event = 'VeryLazy' },
    { 'embark-theme/vim', event = 'VeryLazy' },
    { 'everviolet/nvim', event = 'VeryLazy' },
    { 'fenetikm/falcon', event = 'VeryLazy' },
    { 'folke/tokyonight.nvim', event = 'VeryLazy' },
    { 'gbprod/nord.nvim', event = 'VeryLazy' },
    { 'github-main-user/lytmode.nvim', event = 'VeryLazy' },
    { 'glepnir/zephyr-nvim', event = 'VeryLazy' },
    { 'ishan9299/modus-theme-vim', event = 'VeryLazy' },
    { 'ishan9299/nvim-solarized-lua', event = 'VeryLazy' },
    { 'jim-at-jibba/ariake.nvim', event = 'VeryLazy' },
    { 'judaew/ronny.nvim', event = 'VeryLazy' },
    { 'kaiuri/nvim-juliana', event = 'VeryLazy' },
    { 'kdheepak/monochrome.nvim', event = 'VeryLazy' },
    { 'kevinm6/kurayami.nvim', event = 'VeryLazy' },
    { 'killitar/obscure.nvim', event = 'VeryLazy' },
    { 'klooj/noogies', event = 'VeryLazy' },
    -- 'kuri-sun/yoda.nvim',
    { 'kvrohit/rasmus.nvim', event = 'VeryLazy' },
    { 'kvrohit/substrata.nvim', event = 'VeryLazy' },
    { 'kyazdani42/blue-moon', event = 'VeryLazy' },
    { 'lalitmee/cobalt2.nvim', event = 'VeryLazy' },
    { 'ldelossa/vimdark', event = 'VeryLazy' },
    -- 'lewpoly/sherbet.nvim',
    { 'lmburns/kimbox', event = 'VeryLazy' },
    -- 'loganswartz/sunburn.nvim',
    { 'luisiacc/gruvbox-baby', event = 'VeryLazy' },
    { 'lunacookies/vim-substrata', event = 'VeryLazy' },
    { 'm15a/nvim-srcerite', event = 'VeryLazy' },
    { 'maaslalani/nordbuddy', event = 'VeryLazy' },
    { 'marko-cerovac/material.nvim', event = 'VeryLazy' },
    { 'maxmx03/fluoromachine.nvim', event = 'VeryLazy' },
    { 'mcauley-penney/techbase.nvim', event = 'VeryLazy' },
    { 'mellow-theme/mellow.nvim', event = 'VeryLazy' },
    { 'metalelf0/jellybeans-nvim', event = 'VeryLazy' },
    { 'mhartington/oceanic-next', event = 'VeryLazy' },
    { 'miikanissi/modus-themes.nvim', event = 'VeryLazy' },
    { 'navarasu/onedark.nvim', event = 'VeryLazy' },
    -- 'neanias/everforest-nvim',
    -- 'neko-night/nvim',
    { 'niyabits/calvera-dark.nvim', event = 'VeryLazy' },
    { 'novakne/kosmikoa.nvim', event = 'VeryLazy' },
    { 'ntk148v/slack.nvim', event = 'VeryLazy' },
    { 'nvim-mini/mini.nvim', event = 'VeryLazy' },
    { 'nvimdev/zephyr-nvim', event = 'VeryLazy' },
    { 'nxvu699134/vn-night.nvim', event = 'VeryLazy' },
    { 'nyngwang/nvimgelion', event = 'VeryLazy' },
    { 'nyoom-engineering/oxocarbon.nvim', event = 'VeryLazy' },
    { 'ofirgall/ofirkai.nvim', event = 'VeryLazy' },
    { 'olimorris/onedark.nvim', event = 'VeryLazy' },
    { 'olivercederborg/poimandres.nvim', event = 'VeryLazy' },
    { 'oxfist/night-owl.nvim', event = 'VeryLazy' },
    { 'phha/zenburn.nvim', event = 'VeryLazy' },
    { 'pmouraguedes/neodarcula.nvim', event = 'VeryLazy' },
    { 'polirritmico/monokai-nightasty.nvim', event = 'VeryLazy' },
    { 'projekt0n/github-nvim-theme', event = 'VeryLazy' },
    { 'ptdewey/darkearth-nvim', event = 'VeryLazy' },
    { 'ptdewey/monalisa-nvim', event = 'VeryLazy' },
    { 'qaptoR-nvim/chocolatier.nvim', event = 'VeryLazy' },
    { 'rafamadriz/neon', event = 'VeryLazy' },
    { 'ramojus/mellifluous.nvim', event = 'VeryLazy' },
    { 'ray-x/aurora', event = 'VeryLazy' },
    -- 'ray-x/starry.nvim',
    { 'rebelot/kanagawa.nvim', event = 'VeryLazy' },
    -- 'ribru17/bamboo.nvim',
    { 'rmehri01/onenord.nvim', event = 'VeryLazy' },
    -- 'rockerBOO/boo-colorscheme-nvim',
    { 'rockyzhang24/arctic.nvim', event = 'VeryLazy' },
    -- 'romainl/Apprentice',
    { 'roobert/palette.nvim', event = 'VeryLazy' },
    { 'rose-pine/neovim', event = 'VeryLazy' },
    { 'sainnhe/edge', event = 'VeryLazy' },
    -- 'sainnhe/everforesT',
    { 'sainnhe/gruvbox-material', event = 'VeryLazy' },
    { 'sainnhe/sonokai', event = 'VeryLazy' },
    { 'samharju/serene.nvim', event = 'VeryLazy' },
    { 'samharju/synthweave.nvim', event = 'VeryLazy' },
    { 'savq/melange-nvim', event = 'VeryLazy' },
    { 'scottmckendry/cyberdream.nvim', event = 'VeryLazy' },
    -- 'shaunsingh/moonlight.nvim',
    { 'shaunsingh/nord.nvim', event = 'VeryLazy' },
    { 'shaunsingh/seoul256.nvim', event = 'VeryLazy' },
    { 'shaunsingh/solarized.nvim', event = 'VeryLazy' },
    { 'slugbyte/lackluster.nvim', event = 'VeryLazy' },
    -- 'sonjiku/yawnc.nvim',
    { 'sontungexpt/witch', event = 'VeryLazy' },
    { 'svermeulen/text-to-colorscheme', event = 'VeryLazy' },
    { 'svrana/neosolarized.nvim', event = 'VeryLazy' },
    { 'tanvirtin/monokai.nvim', event = 'VeryLazy' },
    { 'tanvirtin/nvim-monokai', event = 'VeryLazy' },
    -- 'theniceboy/nvim-deus',
    { 'thesimonho/kanagawa-paper.nvim', event = 'VeryLazy' },
    { 'tiagovla/tokyodark.nvim', event = 'VeryLazy' },
    { 'titanzero/zephyrium', event = 'VeryLazy' },
    { 'tjdevries/colorbuddy.nvim', event = 'VeryLazy' },
    { 'tomasiser/vim-code-dark', event = 'VeryLazy' },
    { 'uhs-robert/oasis.nvim', event = 'VeryLazy' },
    { 'uloco/bluloco.nvim', event = 'VeryLazy' },
    { 'uncleTen276/dark_flat.nvim', event = 'VeryLazy' },
    { 'vigoux/oak', event = 'VeryLazy' },
    { 'windwp/wind-colors', event = 'VeryLazy' },
    { 'wuelnerdotexe/vim-enfocado', event = 'VeryLazy' },
    { 'wurli/cobalt.nvim', event = 'VeryLazy' },
    { 'xero/miasma.nvim', event = 'VeryLazy' },
    { 'yazeed1s/minimal.nvim', event = 'VeryLazy' },
    { 'yazeed1s/oh-lucy.nvim', event = 'VeryLazy' },
    { 'yonlu/omni.vim', event = 'VeryLazy' },
    { 'zenbones-theme/zenbones.nvim', event = 'VeryLazy' },
    { 'zootedb0t/citruszest.nvim', event = 'VeryLazy' },
    { 'olimorris/onedarkpro.nvim', event = 'VeryLazy' },
}
