local global_opts = {
    termguicolors = true,
    background = 'light',
    autoread = true,
    autowrite = false,
    cmdheight = 1,
    completeopt = { 'menuone', 'popup', 'noinsert', 'noselect' },
    ignorecase = true,
    maxsearchcount = 9999,
    messagesopt = 'hit-enter,history:10000',
    mouse = '',
    number = true,
    report = 999999,
    scrollback = 100000,
    shortmess = 'aotTOsWAIcCFq',
    showcmd = false,
    showcmdloc = 'statusline',
    showmode = false,
    splitright = true,
    swapfile = false,
    timeout = false,
    ttimeout = false,
    undofile = true,
    undolevels = 999999,
    keywordprg = '',
    laststatus = 3,
    relativenumber = false,
    cpoptions = 'aAceFs_',
    undoreload = 999999,
    sessionoptions = { 'buffers', 'curdir', 'folds', 'globals', 'help', 'localoptions', 'resize', 'tabpages', 'terminal', 'winpos', 'winsize' },
}
for k, v in pairs(global_opts) do
    vim.opt[k] = v
end
