# exec /home/caio/.cargo/bin/swww-daemon
# exec /home/caio/bin/walls
# exec /home/caio/bin/walls-timer 15
# exec swaylock
# exec kitty --single-instance --start-as hidden
# exec kitty
# exec kanshi
# exec "$HOME/.local/lib/cache-git-service"

# exec clipmon
# exec mylock
# exec /home/caio/.local/lib/kde-mime-update
# exec /home/caio/bin/rules-iptables-tor
