input type:pointer {
    accel_profile adaptive
    dwt enabled
    pointer_accel -1
}

input type:keyboard {
    repeat_delay 200
    repeat_rate 75
    xkb_layout br
    xkb_numlock disabled
}

input type:touchpad {
    drag enabled
    tap enabled
}

# input 1:1:AT_Translated_Set_2_keyboard events disabled
# input type:touchpad events disabled_on_external_mouse
